kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs-airflow
  namespace: airflow
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dags-airflow
  namespace: airflow
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-airflow-postgresql-0
  namespace: airflow
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-db-airflow-redis-0
  namespace: airflow
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
